// Autogenerated using cbuild
System.config({
	map: {
		"av-ts": "node_modules/av-ts",
		"systemjs-hot-reloader": "node_modules/systemjs-hot-reloader",
		"vue": "node_modules/vue",
		"vue-hot-reload-api": "node_modules/vue-hot-reload-api"
	},
	meta: {
		"node_modules/*": { globals: { process: "node_modules/cbuild/process-dev.js" } }
	},
	packages: {
		"av-ts": { main: "dist/index.js" },
		"systemjs-hot-reloader": { main: "hot-reloader.js" },
		"vue": { main: "dist/vue.common.js" },
		"vue-hot-reload-api": { main: "index.js" }
	}
});
